listen:
  - address: '127.0.0.1:8314'
    parsers: ['http/1', 'tls']

rules:
  # Only allow services ending with following domain names 
  - type: filter 
    names:
      - example.com
      - google.com
      - internal.consul

  # Apply rewrite rules `memes.internal.consul` -> `memes.consul` 
  - type: rewrite
    matcher: '(?P<svc>[a-z.]+)\.internal\.consul'
    replacer: '$svc.consul'

  # Explicitly redirect `google.com` to localhost
  - type: constant 
    name: google.com
    ips: 
    - 127.0.0.1
        
  # Explicitly update port for google.com
  - type: constant 
    name: google.com
    ports: 
    - 8314:9988 

  # Use google's dns 
  - type: dns 
  # Perform srv lookups for enabled domains 
    srv:
      - example.com
      - my.domain
    address: 8.8.8.8:53
    strategy: Ipv6thenIpv4

  # When all fails sink traffic to 
  # 127.0.0.1:6666
  - type: fallback
    address: '127.0.0.1:6666'
